version: "3.4"

services:

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

